"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-20

Written by hand rather than autogenerated, because two of the indexes here are partial
and Alembic's autogenerate does not reliably round-trip `postgresql_where`.
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # The enum types are created once, explicitly, up front — `content_status` is used
    # by two tables, and letting create_table emit the CREATE TYPE would try to create
    # it twice. `create_type=False` on the column definitions below says "this type
    # already exists, just reference it".
    user_role = postgresql.ENUM("editor", "admin", name="user_role", create_type=False)
    content_status = postgresql.ENUM("draft", "published", name="content_status", create_type=False)
    artwork_kind = postgresql.ENUM(
        "poster", "banner", "thumbnail", name="artwork_kind", create_type=False
    )
    owner_type = postgresql.ENUM("show", "episode", name="owner_type", create_type=False)
    publish_status = postgresql.ENUM(
        "running", "succeeded", "failed", "noop", name="publish_status", create_type=False
    )

    bind = op.get_bind()
    for enum in (user_role, content_status, artwork_kind, owner_type, publish_status):
        enum.create(bind, checkfirst=True)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("email", sa.String(255), nullable=False, unique=True),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("role", user_role, nullable=False),
    )

    op.create_table(
        "shows",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("slug", sa.String(255), nullable=False, unique=True),
        sa.Column("title", sa.String(500), nullable=False),
        sa.Column("synopsis", sa.Text()),
        # Nullable: the seed contains a show with no section, and it must still load.
        sa.Column("section", sa.String(100)),
        sa.Column(
            "categories",
            postgresql.ARRAY(sa.String()),
            nullable=False,
            server_default="{}",
        ),
        sa.Column("status", content_status, nullable=False, server_default="draft"),
        sa.Column("featured", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    # Serves the publish snapshot query and the CMS section filter.
    op.create_index("ix_shows_status_section", "shows", ["status", "section"])

    op.create_table(
        "seasons",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "show_id",
            sa.Integer(),
            sa.ForeignKey("shows.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(500)),
        sa.UniqueConstraint("show_id", "number", name="uq_seasons_show_number"),
        sa.CheckConstraint("number >= 0", name="ck_seasons_number_nonneg"),
    )
    op.create_index("ix_seasons_show_id", "seasons", ["show_id"])

    op.create_table(
        "episodes",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "season_id",
            sa.Integer(),
            sa.ForeignKey("seasons.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("external_id", sa.String(100)),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(500), nullable=False),
        sa.Column("synopsis", sa.Text()),
        # Nullable: publish-blocking, not insert-blocking.
        sa.Column("duration_seconds", sa.Integer()),
        sa.Column("language", sa.String(16), nullable=False),
        sa.Column("content_group", sa.String(255)),
        sa.Column("status", content_status, nullable=False, server_default="draft"),
        sa.Column("seed_issue", sa.Text()),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.create_index("ix_episodes_external_id", "episodes", ["external_id"])
    op.create_index("ix_episodes_season_number", "episodes", ["season_id", "number"])
    # The challenge's hard rule. Partial, because content_group is optional and many
    # rows legitimately share NULL.
    op.create_index(
        "uq_episodes_content_group_language",
        "episodes",
        ["content_group", "language"],
        unique=True,
        postgresql_where=sa.text("content_group IS NOT NULL"),
    )

    op.create_table(
        "artwork",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("owner_type", owner_type, nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("kind", artwork_kind, nullable=False),
        sa.Column("storage_key", sa.String(500), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(100), nullable=False),
        sa.Column("checksum", sa.String(64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        # One image per slot; re-uploading replaces rather than accumulates.
        sa.UniqueConstraint("owner_type", "owner_id", "kind", name="uq_artwork_owner_kind"),
    )

    op.create_table(
        "publish_runs",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True)),
        sa.Column("actor_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="SET NULL")),
        sa.Column("status", publish_status, nullable=False),
        sa.Column("counts", sa.JSON()),
        sa.Column("catalog_key", sa.String(500)),
        sa.Column("checksum", sa.String(64)),
        sa.Column("error", sa.Text()),
        sa.Column("is_current", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # At most one live catalogue, enforced by the database rather than by convention.
    # Doubles as the lookup index for GET /catalog.
    op.create_index(
        "uq_publish_runs_single_current",
        "publish_runs",
        ["is_current"],
        unique=True,
        postgresql_where=sa.text("is_current"),
    )


def downgrade() -> None:
    op.drop_table("publish_runs")
    op.drop_table("artwork")
    op.drop_table("episodes")
    op.drop_table("seasons")
    op.drop_table("shows")
    op.drop_table("users")
    for name in (
        "publish_status",
        "owner_type",
        "artwork_kind",
        "content_status",
        "user_role",
    ):
        op.execute(f"DROP TYPE IF EXISTS {name}")
